### ISSUE TITLE
Button text 

### ISSUE THREAD

**Issue by Tindyy** [misspastelwitch/fix-the-flow-interactive-website#6]
![image](https://github.com/user-attachments/assets/6103c63b-09b4-4649-b8e3-14f07fbb9232)

Dit is wat er gebeurt wanneer je op een button clickt dus mijn advies zou zijn om voor de buttons een hover effect en een active te maken in de code en zorg dat de text blijft staan. Evt zou je wel een soort kleine animatie kunnen toevoegen.

**Comment by misspastelwitch** [comment]
Ik heb de animatie nu verwijderd, bedankt!
